### ISSUE TITLE
With ⁨2.1.57 (6b7d372c)⁩ cuts the bottom tab

### ISSUE THREAD

**Issue by Gravity2106** [AnKing-Memberships/The-KING-of-Button-Add-ons#21]
![Sin título](https://user-images.githubusercontent.com/45825337/215368616-dc3afe24-1860-4f66-a3d8-5a1374839918.png)

**Comment by AnKingMed** [comment]
My understanding is that 2.1.57 changed a bunch of styling. I don't have plans to update any addons for 2.1.57 for sometime and plan to stay on 2.1.56 for a bit. Thanks for reporting this. We'll get to it eventually

**Comment by Rahey94** [comment]
I just want to chime in and say I have the same issue (see picture). Not a huge deal for an otherwise fantastic add-on, but it does make the bottom bar a little unsightly. Looking forward to the fix!

 
![image](https://user-images.githubusercontent.com/54212141/215433105-bba1a2ba-7e49-4749-8382-7aba1ef0fded.png)

**Comment by Erik262** [comment]
In the folder of this addon, there is an "answer_buttons.py" file. By changing the button height to 20 and adding "transform: translate(0, 5px);" above "%(OUTLINE)s" in the "botom_buttons_css" did the trick for me.

**Comment by Gravity2106** [comment]
Good to know! That will probably could patch this until Anking has time.

Thank you everyone 👍

**Comment by Rahey94** [comment]
> In the folder of this addon, there is an "answer_buttons.py" file. By changing the button height to 20 and adding "transform: translate(0, 5px);" above "%(OUTLINE)s" in the "botom_buttons_css" did the trick for me.

Thanks so much for the tip! This fixed the problem for me as well.

**Comment by AnKingMed** [comment]
@abdnh do you have time to make this update to the add-on for 2.1.57+?
