### ISSUE TITLE
Is there a way to reposition the bottom bar (like to the Sides or to the middle). That will be convenient for reviewing in touch screen displays . Thank You

### ISSUE THREAD

**Issue by fredjoe7** [AnKing-Memberships/The-KING-of-Button-Add-ons#24]

**Comment by AnKingMed** [comment]
This addon doesn't have the ability to do that. I'm not even sure if that's possible to be honest

**Comment by fredjoe7** [comment]
i am able to do it with the No Distraction Full Screen add On.  
Previously i used advanced bottom bar add on and No distraction full screen add on to customize the bottom bar as well as change its position. Then i got some issues with both addons, as they were not functioning well together.
Now i am able to run both King of button addon and No distraction full screen to customize as well as reposition bottom bar.

But..
one thing thats missing from the advanced bottom bar add on is there no way to add buttons for skip, undo etc.. which i found useful when reviewing .

Can you bring the option to add skip and undo buttons in the king of button add on ?

**Comment by AnKingMed** [comment]
This addon just restylizes the buttons and doesn't actually adjust them. I don't have any plans to update it beyond that at the moment.  It would probably be better to update the other addons you mentioned
